name: CI WORKFLOW

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with: 
          node-version: "16"

      - name: Install dependencies
        run: npm install

      - name: Compile TS
        run: tsc index.ts

      - name: Run code
        run: node index.js
